
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # Disabling Edge to resolve 500 Internal Server Errors in Next.js 15
  NEXT_USE_NETLIFY_EDGE = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
